name: karrigo-dev-ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set-up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the application
        run: |
          mvn clean
          mvn -B package -DskipTests=true --file pom.xml